service:
  apm:
    enabled: true
    loglevel: INFO
  canary:
    enabled: false
  containers:
    env:
      - name: es_nodes
        value: "vpc-ccgf-qastaging-hawk-es-6qjdyfhrquylf6aozxnbegu6bm.us-west-2.es.amazonaws.com"
      - name: es_port
        value: "80"
      - name: CMS_BASE_URL
        value: "configuration-manager"
  image:
    repository: infacloud-hawk-dev.jfrog.io/ccgf-search-service:1.5.0.252.1
