apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-ccgf-devci-metadata-mgmt
  namespace: ccgf-devci-metadata-mgmt
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '${"ns-"+parameters.namespace}'
  namespace: ccgf-devci-metadata-mgmt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns-ccgf-devci-metadata-mgmt
subjects:
  - kind: ServiceAccount
    name: ccgf-istioctl-pod-sa
    namespace: '${ parameters.namespace}'
